repos:
  - repo: https://github.com/psf/black
    rev: main
    hooks:
      - id: black
        args: [--line-length=88]
        pass_filenames: false

  - repo: https://github.com/PyCQA/pylint
    rev: main
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
        pass_filenames: false

  - repo: https://github.com/PyCQA/autoflake
    rev: main
    hooks:
      - id: autoflake
        args: [--in-place, --remove-unused-variables, --recursive, .]
        pass_filenames: false

  - repo: https://github.com/PyCQA/isort
    rev: main
    hooks:
      - id: isort
        args: [--recursive, .]
        pass_filenames: false
